-- Таблица Import: подмножество полей Transactions + поля состояния импорта и снимка количеств (как в Main).
-- Структура синхронизирована с боевой БД (уточнения ENUM Import / индекс ERP_ID).
-- Выполнить один раз; при «already exists» не повторять без DROP.

CREATE TABLE IF NOT EXISTS `Import` (
    `ERP_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `id` int unsigned NOT NULL AUTO_INCREMENT,
    `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created_by` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `updated_by` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `linked_transaction` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `type` enum('change','move') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'change',
    `where_from` enum('внешний','закупка','склад','цех','собственное производство') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'внешний',
    `where_to` enum('склад','отгрузка','брак','изделие') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'изделие',
    `Quantity_of_parts_total` bigint NOT NULL DEFAULT 0,
    `Quantity_change` bigint NOT NULL DEFAULT 0,

    `Quantity_in_transactions` bigint NOT NULL DEFAULT 0,
    `inProcess_purchase` bigint NOT NULL DEFAULT 0,
    `inProcess_manufacturing` bigint NOT NULL DEFAULT 0,
    `Quantity_in_warehouse` bigint NOT NULL DEFAULT 0,
    `Quantity_in_kitting` bigint NULL DEFAULT 0,
    `Quantity_on_shopfloor` bigint NOT NULL DEFAULT 0,
    `Quantity_implemented` bigint NOT NULL DEFAULT 0,
    `Quantity_shipped` bigint NOT NULL DEFAULT 0,
    `Quantity_of_losses` bigint NOT NULL DEFAULT 0,
    `Quantity_avaliable` bigint NULL,
    `Needed_new` bigint NOT NULL DEFAULT 0,
    `Cant_be_cancelled` bigint NOT NULL DEFAULT 0,
    `Suggestion` enum('Импортировать','Заменить','Отменить','') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
    `Order_import` enum('Ожидание','Импортировать','Отменить','Выполнить') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Ожидание',
    `Status_import` enum('Новая','Импортировано','Заменено','Отменено') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Новая',

    `Project` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Target_assembly` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Supplied_component_number` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Component_revision` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Component_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Quantity_in_target_assembly` bigint NOT NULL DEFAULT 0,
    `Quantity_of_target_assemblies` bigint NOT NULL DEFAULT 0,
    `Component_type` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `For_supplied_as_assembly_components_provided_by_supplier` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Components_quantity_in_assembly` bigint NOT NULL DEFAULT 0,
    `Assembly_batch_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    `Assembly_batch_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Assembly_batch_status` enum('Нет спецификации','Ожидает определения','В закупке/изготовлении','В комплектации','В сборке','Готов') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    `Assembly_batch_priority` int NULL DEFAULT NULL,
    `Part_material` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Producer` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Catalogue_number` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Producer_article` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Distributer` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Distributer_article` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `MBOM_type` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Mass_kg` double NULL,
    `Unit_of_measure` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Height` double NULL,
    `Width` double NULL,
    `Length` double NULL,
    `Advanced_group` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Address` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Document_no` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Zakaz_no` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Date_needed` date NULL,
    `Date_expected` date NULL,
    `Cost_total_rub` float NULL,
    `Supplier` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Contractor_INN` varchar(12) CHARACTER SET ascii COLLATE ascii_general_ci NULL,
    `Contractor_KPP` char(9) CHARACTER SET ascii COLLATE ascii_general_ci NULL,
    `Price_of_single_unit` double NULL,
    `Location` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Source` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `Initial_doc_no` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,

    PRIMARY KEY (`id`),
    KEY `idx_import_erp_id` (`ERP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
