-- Таблица location_rules: правила назначения адреса хранения по условиям.
-- В отличие от recommend_rules, целевое поле: default_address -> Cells.id.

CREATE TABLE IF NOT EXISTS `location_rules` (
    `id` int unsigned NOT NULL AUTO_INCREMENT,
    `priority` int NOT NULL COMMENT 'Приоритет применения правил и условий',
    `project` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ANY'
        COMMENT 'ANY или список проектов через ", ", например: 0012, 0014',
    `rule_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
        COMMENT 'Имя правила; повторяется для всех условий одного правила',
    `default_address` int unsigned NULL COMMENT 'Ссылка на ячейку хранения Cells.id',
    `logic_operator` enum('WHERE','OR','AND') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `field_name` enum(
        'ANY',
        'ERP_ID',
        'id',
        'created_at',
        'updated_at',
        'created_by',
        'updated_by',
        'changed_by',
        'linked_transaction',
        'type',
        'where_from',
        'where_to',
        'Quantity_of_parts_total',
        'Quantity_change',
        'Status_transaction',
        'Project',
        'Target_assembly',
        'Supplied_component_number',
        'Component_revision',
        'Component_name',
        'Quantity_in_target_assembly',
        'Quantity_of_target_assemblies',
        'Components_quantity_in_assembly',
        'Component_type',
        'For_supplied_as_assembly_components_provided_by_supplier',
        'Part_material',
        'Producer',
        'Catalogue_number',
        'Producer_article',
        'Distributer',
        'Distributer_article',
        'MBOM_type',
        'Mass_kg',
        'Unit_of_measure',
        'Height',
        'Width',
        'Length',
        'Advanced_group',
        'Address',
        'Recommend_purchprod',
        'Order_purch',
        'Order_wh',
        'Order_prod',
        'Order_OTK',
        'Order_sv',
        'Recommend_wh',
        'Quantity_ordered',
        'Replace_to',
        'Rework_to',
        'Rework_from',
        'Status_warehouse',
        'Document_no',
        'Document_date',
        'Zakaz_no',
        'Date_needed',
        'Date_expected',
        'Cost_total_rub',
        'Supplier',
        'Price_of_single_unit',
        'Location',
        'Source',
        'Initial_doc_no',
        'Assembly_batch_id',
        'Assembly_batch_name',
        'Assembly_batch_status',
        'Assembly_batch_priority'
    ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `compare_operator` enum('=','<>','>','<','>=','<=','like','not like') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `condition_value` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_location_rules_priority` (`priority`),
    KEY `idx_location_rules_rule_id` (`rule_id`),
    KEY `idx_location_rules_project` (`project`),
    KEY `idx_location_rules_default_address` (`default_address`),
    CONSTRAINT `fk_location_rules_default_address`
        FOREIGN KEY (`default_address`) REFERENCES `Cells` (`id`)
        ON UPDATE CASCADE
        ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
