-- Таблица recommend_rules: правила назначения рекомендаций для recommend_purchprod.
-- Данные ниже перенесены из templates/recommend_rules.xlsx.
-- Строки id 1..56 считаются управляемыми шаблоном и обновляются этим скриптом.

CREATE TABLE IF NOT EXISTS `recommend_rules` (
    `id` int unsigned NOT NULL AUTO_INCREMENT,
    `priority` int NOT NULL COMMENT 'Приоритет применения правил и условий',
    `project` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ANY'
        COMMENT 'ANY или список проектов через ", ", например: 0012, 0014',
    `rule_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
        COMMENT 'Имя правила; повторяется для всех условий одного правила',
    `recommend_purchprod` enum('В закупку','В собственное производство') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `logic_operator` enum('WHERE','OR','AND') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `field_name` enum(
        'ANY',
        'ERP_ID',
        'id',
        'created_at',
        'updated_at',
        'created_by',
        'updated_by',
        'changed_by',
        'linked_transaction',
        'type',
        'where_from',
        'where_to',
        'Quantity_of_parts_total',
        'Quantity_change',
        'Status_transaction',
        'Project',
        'Target_assembly',
        'Supplied_component_number',
        'Component_revision',
        'Component_name',
        'Quantity_in_target_assembly',
        'Quantity_of_target_assemblies',
        'Components_quantity_in_assembly',
        'Component_type',
        'For_supplied_as_assembly_components_provided_by_supplier',
        'Part_material',
        'Producer',
        'Catalogue_number',
        'Producer_article',
        'Distributer',
        'Distributer_article',
        'MBOM_type',
        'Mass_kg',
        'Unit_of_measure',
        'Height',
        'Width',
        'Length',
        'Advanced_group',
        'Address',
        'Recommend_purchprod',
        'Order_purch',
        'Order_wh',
        'Order_prod',
        'Order_OTK',
        'Order_sv',
        'Recommend_wh',
        'Quantity_ordered',
        'Replace_to',
        'Rework_to',
        'Rework_from',
        'Status_warehouse',
        'Document_no',
        'Document_date',
        'Zakaz_no',
        'Date_needed',
        'Date_expected',
        'Cost_total_rub',
        'Supplier',
        'Price_of_single_unit',
        'Location',
        'Source',
        'Initial_doc_no',
        'Assembly_batch_id',
        'Assembly_batch_name',
        'Assembly_batch_status',
        'Assembly_batch_priority'
    ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `compare_operator` enum('=','<>','>','<','>=','<=','like','not like') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `condition_value` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_recommend_rules_priority` (`priority`),
    KEY `idx_recommend_rules_rule_id` (`rule_id`),
    KEY `idx_recommend_rules_project` (`project`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DELETE FROM `recommend_rules`
WHERE `id` BETWEEN 1 AND 56;

INSERT INTO `recommend_rules` (
    `id`,
    `priority`,
    `project`,
    `rule_id`,
    `recommend_purchprod`,
    `logic_operator`,
    `field_name`,
    `compare_operator`,
    `condition_value`
) VALUES
    (1, 100, 'ANY', 'PKI_to_purch', 'В закупку', 'WHERE', 'Component_type', '=', 'Покупное изделие'),
    (2, 200, 'ANY', 'PKI_to_purch', 'В закупку', 'OR', 'Component_type', '=', 'Стандартное изделие'),
    (6, 600, '0012, 0014', 'ownProd_parts', 'В собственное производство', 'WHERE', 'MBOM_type', '=', '3D printing'),
    (10, 1000, 'ANY', 'ownProd_KIT', 'В собственное производство', 'WHERE', 'Component_type', '=', 'Комплект'),
    (11, 1100, 'ANY', 'ownProd_KIT', 'В собственное производство', 'OR', 'Component_type', '=', 'Комплекс'),
    (15, 1500, 'ANY', 'ownProd_assy', 'В собственное производство', 'WHERE', 'MBOM_type', '=', 'Assembly of electrical cabinets and units'),
    (16, 1600, 'ANY', 'ownProd_assy', 'В собственное производство', 'OR', 'MBOM_type', 'like', 'KIT'),
    (17, 1700, 'ANY', 'ownProd_assy', 'В собственное производство', 'OR', 'MBOM_type', 'like', 'Normal assy'),
    (18, 1800, 'ANY', 'ownProd_assy', 'В собственное производство', 'OR', 'MBOM_type', 'like', 'Accurate assy'),
    (22, 2200, 'ANY', 'default', 'В закупку', 'WHERE', 'Component_type', '=', 'Деталь'),
    (23, 2300, 'ANY', 'default', 'В закупку', 'OR', 'Component_type', '=', 'Сборочная единица')
ON DUPLICATE KEY UPDATE
    `priority` = VALUES(`priority`),
    `project` = VALUES(`project`),
    `rule_id` = VALUES(`rule_id`),
    `recommend_purchprod` = VALUES(`recommend_purchprod`),
    `logic_operator` = VALUES(`logic_operator`),
    `field_name` = VALUES(`field_name`),
    `compare_operator` = VALUES(`compare_operator`),
    `condition_value` = VALUES(`condition_value`);
